### ISSUE TITLE
stopped working after update to Home Assistant 0.117.6

### ISSUE THREAD

**Issue by fireheadman** [MatthewFlamm/nwsradar#15]
Just getting a black screen now.   It stopped working after update to Home Assistant 0.117.6
Unsure what broke or caused it to break.

was previously on 0.116.x and it works perfect

**Comment by fireheadman** [comment]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/19847195/98904857-9f76c000-2477-11eb-95a8-6417a72c1528.png">

**Comment by MatthewFlamm** [comment]
Thanks for the report! I think this is related to #4 if you don't have anything in your logs

**Comment by fireheadman** [comment]
Nothing in logs.

**Comment by MatthewFlamm** [comment]
After investigating, it looks like this is the same issue as #4.  There are no image files listed for this radar.

![Screenshot_20201112-092753](https://user-images.githubusercontent.com/39341281/98952505-8860be00-24c9-11eb-9b9b-852526819d9a.png)

**Comment by fireheadman** [comment]
Very odd.   Our lovely government at its best

**Comment by fireheadman** [comment]
its working now...
<img width="653" alt="image" src="https://user-images.githubusercontent.com/19847195/99029934-073d1180-2531-11eb-8856-9cbffbf2daa3.png">
