### ISSUE TITLE
Always showing "something" on my radar

### ISSUE THREAD

**Issue by clandestine-avocado** [MatthewFlamm/nwsradar#3]
So I added all 6 radar types in my config and created 6 cards, one for each so I could see the differences. Each has show something over Washington DC every single day for a week - even when it's dead clear, as it is right now. 

What is being shown, if it's dead clear outside? Just hot air coming from all the politicians?
![6 weather cards](https://user-images.githubusercontent.com/56581105/75084653-69f80400-54ef-11ea-9f34-b9c59d44ba15.png)

**Comment by MatthewFlamm** [comment]
See this https://www.weather.gov/mkx/using-radar

**Comment by clandestine-avocado** [comment]
Thanks Matthew - good link. I assume what I'm seeing is "Anomalous Propagation." I just have no idea what would be causing this over Washington DC.

**Comment by MatthewFlamm** [comment]
It happens to all radar stations to different degrees depending on atmospheric conditions.

**Comment by clandestine-avocado** [comment]
Cool - appreciate the response (especially since this isn't really an issue with your project!) It's just odd to me that it's always like this - regardless of atmospheric changes. The actual radar is in Sterling VA - right next to a major airport. I wonder if that has something to do with it.

**Comment by MatthewFlamm** [comment]
I find that when there is a real signal, these artifacts tend not to be present.  I'm going to close this since it isnt related to the retrieval of the radar images as you pointed out.
